---
#------------
# creates the app dir stucture
#------------
- name: create app dir directory structure
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ eyemetric_user }}"
    group: "{{ eyemetric_user }}"
    recurse: true
  loop:
    - "{{ app_dir }}/certs"
    - "{{ app_dir }}/compose"
    - "{{ app_dir }}/config"
    - "{{ app_dir }}/data"
    - "{{ app_dir }}/scripts"
    - "{{ app_dir }}/sites"
    - "{{ app_dir }}/utils"
    - "{{ app_dir }}/logs"

- name: Copy config files to server
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ app_dir }}/compose/{{ item.dest }}"
    owner: "{{ eyemetric_user }}"
    group: "{{ eyemetric_user }}"
  loop:
    - { src: "bashman.j2", dest: "bashman_{{arch}}" }

- name: Ensure the Podman start script is executable
  file:
    path: "{{ app_dir }}/compose/bashman_{{arch}}"
    mode: "0755"
  become: true
  become_user: "{{ eyemetric_user }}"

- name: Copy utility scripts and fr-cli tool and certs
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ eyemetric_user }}"
    group: "{{ eyemetric_group }}"
    mode: "0774"
  loop:
    - { src: "scripts/", dest: "{{ app_dir }}/scripts/" } # Copy the contents of "scripts" to "{{ app_dir }}/scripts"
    - { src: "certs/", dest: "{{ app_dir }}/certs/" } # Copy the contents of "scripts" to "{{ app_dir }}/scripts"
    - { src: "cv-cli", dest: "{{ app_dir }}/utils/fr-cli" } # Copy "cv-cli" to "{{ app_dir }}/utils/fr-cli"

- name: Copy config files to server
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ app_dir }}/config/{{ item.dest }}"
    owner: "{{ eyemetric_user }}"
    group: "{{ eyemetric_user }}"
  loop:
    - { src: "Caddyfile.j2", dest: "Caddyfile" }
    - { src: "rtsp-webrtc.json.j2", dest: "rtsp-webrtc.json" }

# assets useful libs for our sites. used by auth only at the moment.
- name: copy web assets
  ansible.builtin.copy:
    src: ../files/sites/assets
    dest: "{{app_dir}}/sites"
    directory_mode: "777"
    owner: eyemetric # Optional: Specify owner
    group: eyemetric # Optional: Specify group
    mode: "777" # Optional: Set permissions
  become: true # Optional: Use 'become' to become another user, often used for permissions.
