---

- name: Set container manager
  ansible.builtin.set_fact:
    oci_cmd: "podman"

- name: Use podman login so we ca pull our images
  become: false
  register: podman_login
  containers.podman.podman_login:
    username: "{{ docker_login }}"
    password: "{{ docker_pwd }}"
    registry: docker.io

- name: Pull SAFR containers from docker.io
  become: false
  register: docker_pull
  containers.podman.podman_image:
    name: "{{ item.value }}"
  loop: "{{ safr_images | dict2items }}"

- name: Install tools an utilities
  ansible.builtin.include_tasks: install_tools.yml


- name: Create app structure and copy config files
  ansible.builtlin.include_tasks: copy_files.yml


# - name: apply paravision multi gpu workaround
#  include_tasks: pv_multi_gpu_fix.yml


- name: Set unpriviledged port access to start at 80
  lansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    insertafter: EOF
    line: net.ipv4.ip_unprivileged_port_start=80

- name: Reload sysctl.conf
  ansible.builtin.command: sysctl -p


- name: Configure for systemd.
  ansible.builtin.include_tasks: systemd_setup.yml
 # include_tasks: systemd_user_tasks.yml
