---
- name: Install EyeFR (SAFR)
  hosts: all
  become: true
  vars:
    ansible_become_pass: "{{ host_sudo_pass[inventory_hostname] | default(default_sudo_pass) }}"
    release_version: "1.6.2" 
    overwrite_data_vol: false
  roles:
    - { role: paravision.v6, tags: ["paravision"] }
    - { role: eyemetric.eyefr, tags: ["eyefr", "assets"], vars: { app_ver: "{{ release_version }}" }}

  tasks:
    - name: Include quadlet tasks
      include_tasks: tasks/quadlet_config.yml
      vars: 
        arch: "{{ 'gpu' if 'gpu' in group_names else 'cpu' }}"
        pv_images: "{{ pv_gpu_images if 'gpu' in group_names else pv_cpu_images }}"
      tags: 
        - quadlet 
# remember to manually set eyemetric.eyefr/files/compose/vars.yml to the 
# correct app_ver denoted here in release version.
