---
- name: Install EyeFR (SAFR)
  hosts: all
  become: true
  vars:
    ansible_become_pass: "{{ host_sudo_pass[inventory_hostname] | default(default_sudo_pass) }}"
  roles:
    - { role: paravision.v6, tags: ["paravision"] }
    - { role: eyemetric.eyefr, tags: ["eyefr"] }

  tasks:
    - name: set up db data and copy static sites
      tags: ["sites", "data"]
      vars:
        overwrite_data_vol: false
      include_tasks: tasks/install_assets.yml

