---
- name: Check if the data directory is empty
  ansible.builtin.find:
    paths: "{{ app_dir }}/data"
    file_type: directory
  register: data_dir_contents
  tags: ["data"]

- name: Check if the sites directory is empty
  ansible.builtin.find:
    paths: "{{ app_dir }}/sites"
    file_type: any
  register: sites_dir_contents
  tags: ["sites"]

- name: start assets container
  become: false
  register: data_container
  shell: "podman run -d --rm --replace --name assets {{ safr_images.assets }}"
  tags: ["sites", "data"]
# if we run into a situation where data exists (it shouldn't since this is install not update)
# NOTE: This is all a bit of a defensive hack. We should really be doing data migrations.
# this is just a precaution in the case where we run ansible and there's existing data. destroying that would be bad.
- name: Backup Data volumes before overwriting any existing data
  when: overwrite_data_vol and data_dir_contents.matched > 0
  tags: ["data"]
  block:
    - name: backup existing data volumes to /tmp
      become: false
      community.general.archive:
        path: "{{ app_dir }}/data"
        # dest: "/tmp/data_vol.bk.tgz"
        dest: "/tmp/data_vol.bk.tar.gz.{{app_ver}}.{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
        owner: "{{ eyemetric_user }}"
        group: "{{ eyemetric_group }}"
        mode: "0774"

- name: init data volumes
  when: overwrite_data_vol or data_dir_contents.matched == 0
  tags: ["data"]
  block:
    - name: copy data volumes from assets to tmp dir
      become: no
      register: data_copy
      shell: |
        {{ oci_cmd  }} cp assets:/safr_pgdata.tar.gz /tmp
        {{ oci_cmd  }} cp assets:/pvdb_pgdata.tar.gz /tmp
    - debug:
        var: data_copy
    - debug:
        var: data_container

    - name: Extract data volume archives to volume location
      unarchive:
        src: "{{ item }}"
        dest: "{{ app_dir }}/data"
        remote_src: yes
        owner: "{{ eyemetric_user }}"
        group: "{{ eyemetric_group }}"
        mode: "0774"
      loop:
        - /tmp/safr_pgdata.tar.gz
        - /tmp/pvdb_pgdata.tar.gz

- name: prepare sites
  #when: sites_dir_contents.matched > 0
  when: sites_dir_contents.matched > 0
  tags: ["sites"]
  block:
    - name: backup existing sites to /tmp
      become: false
      community.general.archive:
        path: "{{ app_dir }}/sites"
        dest: "/tmp/sites.bk.tar.gz.{{app_ver}}.{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
        owner: "{{ eyemetric_user }}"
        group: "{{ eyemetric_group }}"
        mode: "0774"

    #   - name: Find Sites files and subdirectories
    #     ansible.builtin.find:
    #       paths: "{{app_dir}}/sites"
    #       file_type: any
    #       hidden: yes # Set to 'yes' if you also want to delete hidden files and subdirectories
    #     register: files_to_delete

    #   - name: Delete all files and subdirectories
    #     ansible.builtin.file:
    #       path: "{{ item.path }}"
    #       state: absent
    #     loop: "{{ files_to_delete.files }}"

    - name: copy sites from assets to tmp dir
      become: false
      register: data_copy
      shell: |
        podman cp assets:/cam-app {{app_dir}}/sites
        podman cp assets:/fr-analyze {{app_dir}}/sites

- name: Stop podman assets container
  become: false
  tags: ["data", "sites"]
  containers.podman.podman_container:
    name: assets
    state: stopped
